set role ssbench;
set search_path=:DB_SCHEMA_NAME,public;
:EXPLAIN_ANALYZE


SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder_flat
WHERE
  EXTRACT(WEEK FROM LO_ORDERDATE) = 6
  AND LO_ORDERDATE >= to_date('19940101', 'YYYYMMDD')
  AND LO_ORDERDATE <= to_date('19941231', 'YYYYMMDD')
  AND LO_DISCOUNT BETWEEN 5 AND 7
  AND LO_QUANTITY BETWEEN 26 AND 35;